/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package input;
import output.mainoutput;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author acer
 */
public class intwo extends javax.swing.JFrame {

    /**
     * Creates new form intwo
     */

        
    public intwo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcrem1 = new javax.swing.JCheckBox();
        jcrem2 = new javax.swing.JCheckBox();
        jcrem3 = new javax.swing.JCheckBox();
        jcrem4 = new javax.swing.JCheckBox();
        jcrem5 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jtxtattendance = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcoffice = new javax.swing.JCheckBox();
        jbtnverified = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        jlblsem = new javax.swing.JLabel();
        jlblregister = new javax.swing.JLabel();
        jlblname = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlblrevision = new javax.swing.JLabel();
        jlblrev = new javax.swing.JLabel();
        jlbldate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("COMPLIANCE REPORT");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name of Student :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Register No. :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Semester:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Sl No.");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Remark");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("1");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("2");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("3");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("4");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("5");

        jcrem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcrem1.setText("Completed");
        jcrem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcrem1ActionPerformed(evt);
            }
        });

        jcrem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcrem2.setText("Completed");
        jcrem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcrem2ActionPerformed(evt);
            }
        });

        jcrem3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcrem3.setText("Completed");

        jcrem4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcrem4.setText("Completed");

        jcrem5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcrem5.setText("Completed");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Attendance %");

        jtxtattendance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtattendanceActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Office(No dues)");

        jcoffice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcoffice.setText("No  Dues");

        jbtnverified.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnverified.setText("VERIFIED&SAVE");
        jbtnverified.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnverifiedActionPerformed(evt);
            }
        });

        jbtnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnback.setText("BACK");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });

        jtb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Name", "Subject Code"
            }
        ));
        jtb1.setRowHeight(40);
        jScrollPane1.setViewportView(jtb1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbtnback)
                .addGap(157, 157, 157)
                .addComponent(jbtnverified, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jtxtattendance, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jcoffice))
                            .addComponent(jLabel16))
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcrem3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcrem4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcrem5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcrem2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcrem1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jcrem1))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jcrem2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jcrem3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jcrem4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jcrem5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jtxtattendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcoffice)
                        .addGap(53, 53, 53)
                        .addComponent(jbtnverified, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnback))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jlblsem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblsem.setText("sem");

        jlblregister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblregister.setText("reg");

        jlblname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblname.setText("name");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Date :");

        jlblrevision.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblrevision.setText("Revision :");

        jlblrev.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jlbldate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbldate.setText("date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlblrevision)
                            .addGap(18, 18, 18)
                            .addComponent(jlblrev, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jlblname, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlblregister, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jlblsem))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(134, 134, 134)
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(jlbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14))))
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1)
                    .addComponent(jlbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblrevision)
                    .addComponent(jlblrev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jlblsem)
                    .addComponent(jlblregister)
                    .addComponent(jlblname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcrem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcrem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcrem2ActionPerformed

    private void jcrem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcrem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcrem1ActionPerformed

    private void jtxtattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtattendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtattendanceActionPerformed

    private void jbtnverifiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnverifiedActionPerformed
        
        
        float at = Float.parseFloat(jtxtattendance.getText());
        
        if (at<75){
        JOptionPane.showMessageDialog(null,"Attendance < 75","Not Eligible",JOptionPane.ERROR_MESSAGE);
        
        }
        if(at>100){
             JOptionPane.showMessageDialog(null,"Invalide Attendance","Error",JOptionPane.ERROR_MESSAGE);
        }
        int response =  JOptionPane.showConfirmDialog(null, "CONFIRM THAT ALL THE WORK IS COMPLETED ?" , "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(response==JOptionPane.YES_OPTION){
            mainoutput out=new mainoutput();
        out.jlbname.setText(jlblname.getText());
        out.jlbreg.setText(jlblregister.getText());
        out.jlbsem.setText(jlblsem.getText());
        
        out.jlbatte.setText(jtxtattendance.getText());
        out.jlbname2.setText(jlblname.getText());
        out.jlbreg2.setText(jlblregister.getText());
        out.jlbldate.setText(jlbldate.getText());
        
        int row = jtb1.getRowCount();
        for(int i=0;i<row;i++){
            
            if(i==0){
               out.jlbsub1.setText((String) jtb1.getValueAt(0, 0));
               out.jlblcode1.setText((String) jtb1.getValueAt(0,1)); 
            }
            if(i==1){
               out.jlbsub2.setText((String) jtb1.getValueAt(1, 0));
               out.jlbcode2.setText((String) jtb1.getValueAt(1,1));
            }
            if(i==2){
               out.jlbsub3.setText((String) jtb1.getValueAt(2, 0));
               out.jlbcode3.setText((String) jtb1.getValueAt(2,1)); 
            }
            if(i==3){
               out.jlbsub4.setText((String) jtb1.getValueAt(3, 0));
               out.jlbcode4.setText((String) jtb1.getValueAt(3,1)); 
            }
            if(i==4){
               out.jlbsub5.setText((String) jtb1.getValueAt(4, 0));
               out.jlbcode5.setText((String) jtb1.getValueAt(4,1)); 
            }
        }
        
        
        
        
        
        
       
        if(jcrem1.isSelected()){
            out.jlbrem1.setText(jcrem1.getText());
        }
        else{
            out.jlbrem1.setText("Null");
        }
        if(jcrem2.isSelected()){
            out.jlbrem2.setText(jcrem2.getText());
        }
        else{
            out.jlbrem2.setText("Null");
        }
        if(jcrem3.isSelected()){
            out.jlbrem3.setText(jcrem3.getText());
        }
        else{
            out.jlbrem3.setText("Null");
        }if(jcrem4.isSelected()){
            out.jlbrem4.setText(jcrem4.getText());
        }
        else{
            out.jlbrem4.setText("Null");
        }if(jcrem5.isSelected()){
            out.jlbrem5.setText(jcrem5.getText());
        }
        else{
            out.jlbrem5.setText("Null");
        }
        if(jcoffice.isSelected()){
            out.jlboff.setText(jcoffice.getText());
        }
        else{
            out.jlboff.setText("Pending");
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crdb?useSSL=false","root","");
            int reg_no=Integer.parseInt (jlblregister.getText());
            String name = jlblname.getText();
            String sem = jlblsem.getText();
            int rev=Integer.parseInt(jlblrev.getText());
   
            String query = "insert into students(reg_no,name,semester,revision)values (?, ?, ?, ?)";
            PreparedStatement prepstmt = con.prepareStatement(query);
            prepstmt.setInt(1, reg_no);
            prepstmt.setString(2, name);
            prepstmt.setString(3, sem);
            prepstmt.setInt(4, rev);
            prepstmt.execute();
            JOptionPane.showMessageDialog(null, "Data inserted succesfully");
            
            out.setVisible(true);
        }catch(Exception e){
            
        }
        out.setVisible(true);
        
        
        
    
        }else if(response==JOptionPane.NO_OPTION){
            mainoutput out=new mainoutput();
            out.setVisible(false);
        }
    
    }//GEN-LAST:event_jbtnverifiedActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
       inone info = new inone();
            info.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])   {
        {
           
                }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intwo().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnverified;
    private javax.swing.JCheckBox jcoffice;
    private javax.swing.JCheckBox jcrem1;
    private javax.swing.JCheckBox jcrem2;
    private javax.swing.JCheckBox jcrem3;
    private javax.swing.JCheckBox jcrem4;
    private javax.swing.JCheckBox jcrem5;
    public javax.swing.JLabel jlbldate;
    public javax.swing.JLabel jlblname;
    public javax.swing.JLabel jlblregister;
    public javax.swing.JLabel jlblrev;
    private javax.swing.JLabel jlblrevision;
    public static javax.swing.JLabel jlblsem;
    public javax.swing.JTable jtb1;
    private javax.swing.JTextField jtxtattendance;
    // End of variables declaration//GEN-END:variables
}
